use tsn_types::Value;

use super::{
    array, async_, console, crypto, fs, http, io, json, map, math, net, path, primitives, reflect,
    set, sys, time,
};

pub type IntrinsicFn = fn(&mut dyn tsn_types::Context, &[Value]) -> Result<Value, String>;

fn unimpl(_ctx: &mut dyn tsn_types::Context, _args: &[Value]) -> Result<Value, String> {
    Err("Intrinsic not implemented".into())
}

pub static INTRINSIC_TABLE: [IntrinsicFn; 254] = [
    /* 0   */ console::console_log,
    /* 1   */ json::json_parse,
    /* 2   */ json::json_stringify,
    /* 3   */ path::path_normalize,
    /* 4   */ time::time_now,
    /* 5   */ array::array_is_array,
    /* 6   */ |_, a| map::map_new(a),
    /* 7   */ |_, a| map::map_get(a),
    /* 8   */ |_, a| map::map_set(a),
    /* 9   */ |_, a| map::map_has(a),
    /* 10  */ |_, a| io::io_write(a),
    /* 11  */ |_, a| io::io_writeln(a),
    /* 12  */ |_, a| io::io_flush(a),
    /* 13  */ |_, a| io::io_read_line(a),
    /* 14  */ |_, a| io::io_read_all(a),
    /* 15  */ |_, a| map::map_delete(a),
    /* 16  */ |_, a| map::map_clear(a),
    /* 17  */ |_, a| map::map_keys(a),
    /* 18  */ |_, a| map::map_values(a),
    /* 19  */ |_, a| map::map_size(a),
    /* 20  */ |_, a| sys::sys_platform(a),
    /* 21  */ |_, a| sys::sys_cwd(a),
    /* 22  */ |_, a| sys::sys_args(a),
    /* 23  */ |_, a| sys::sys_exit(a),
    /* 24  */ |_, a| sys::sys_env_get(a),
    /* 25  */ |_, a| sys::sys_env_set(a),
    /* 26  */ |_, a| set::set_new(a),
    /* 27  */ |_, a| set::set_add(a),
    /* 28  */ |_, a| set::set_has(a),
    /* 29  */ |_, a| set::set_delete(a),
    /* 30  */ fs::fs_read,
    /* 31  */ fs::fs_write,
    /* 32  */ fs::fs_exists,
    /* 33  */ fs::fs_kind,
    /* 34  */ fs::fs_open,
    /* 35  */ fs::fs_create,
    /* 36  */ fs::fs_read_bytes,
    /* 37  */ fs::fs_read_text,
    /* 38  */ fs::fs_write_bytes,
    /* 39  */ fs::fs_write_text,
    /* 40  */ fs::fs_append_text,
    /* 41  */ fs::fs_stat,
    /* 42  */ fs::fs_mkdir,
    /* 43  */ fs::fs_mkdir_all,
    /* 44  */ fs::fs_read_dir,
    /* 45  */ fs::fs_remove,
    /* 46  */ fs::fs_remove_all,
    /* 47  */ fs::fs_rename,
    /* 48  */ fs::fs_copy,
    /* 49  */ fs::fs_symlink,
    /* 50  */ fs::fs_read_link,
    /* 51  */ fs::fs_watch,
    /* 52  */ fs::fs_temp_dir,
    /* 53  */ |_, a| set::set_clear(a),
    /* 54  */ |_, a| set::set_values(a),
    /* 55  */ |_, a| set::set_size(a),
    /* 56  */ console::console_debug,
    /* 57..59 */ unimpl,
    unimpl,
    unimpl,
    /* 60  */ |_, a| crypto::crypto_sha256(a),
    /* 61  */ |_, a| crypto::crypto_sha512(a),
    /* 62  */ |_, a| crypto::crypto_random_bytes(a),
    /* 63  */ |_, a| crypto::crypto_random_hex(a),
    /* 64  */ |_, a| crypto::crypto_base64_enc(a),
    /* 65  */ |_, a| crypto::crypto_base64_dec(a),
    /* 66  */ |_, a| crypto::crypto_hmac(a),
    /* 67  */ |_, a| crypto::crypto_uuid(a),
    /* 68..69 */ unimpl,
    unimpl,
    /* 70  */ net::net_is_ip,
    /* 71  */ net::net_is_ipv4,
    /* 72  */ net::net_is_ipv6,
    /* 73  */ net::net_join_host_port,
    /* 74  */ net::net_split_host_port,
    /* 75  */ net::net_parse_url,
    /* 76  */ net::net_resolve_url,
    /* 77  */ net::net_parse_query,
    /* 78  */ net::net_build_query,
    /* 79  */ net::net_append_query,
    /* 80  */ net::net_enc_uri_component,
    /* 81  */ net::net_dec_uri_component,
    /* 82  */ net::net_basic_auth,
    /* 83  */ http::http_fetch,
    /* 84  */ http::http_server_create,
    /* 85  */ http::http_server_route,
    /* 86  */ http::http_server_listen,
    /* 87  */ http::http_response_send,
    /* 88..89 */ unimpl,
    unimpl,
    /* 90  */ |_, a| math::math_abs(a),
    /* 91  */ |_, a| math::math_acos(a),
    /* 92  */ |_, a| math::math_asin(a),
    /* 93  */ |_, a| math::math_atan(a),
    /* 94  */ |_, a| math::math_atan2(a),
    /* 95  */ |_, a| math::math_ceil(a),
    /* 96  */ |_, a| math::math_cos(a),
    /* 97  */ |_, a| math::math_exp(a),
    /* 98  */ |_, a| math::math_floor(a),
    /* 99  */ |_, a| math::math_log(a),
    /* 100 */ |_, a| math::math_max(a),
    /* 101 */ |_, a| math::math_min(a),
    /* 102 */ |_, a| math::math_pow(a),
    /* 103 */ |_, a| math::math_random(a),
    /* 104 */ |_, a| math::math_round(a),
    /* 105 */ |_, a| math::math_sin(a),
    /* 106 */ |_, a| math::math_sqrt(a),
    /* 107 */ |_, a| math::math_tan(a),
    /* 108 */ |_, a| math::math_trunc(a),
    /* 109 */ |_, a| math::math_sign(a),
    /* 110 */ |_, a| math::math_nan(a),
    /* 111 */ |_, a| math::math_infinity(a),
    /* 112 */ primitives::symbol_iterator,
    /* 113 */ primitives::symbol_async_iterator,
    /* 114 */ |_, a| reflect::reflect_define_meta(a),
    /* 115 */ |_, a| reflect::reflect_get_meta(a),
    /* 116 */ |_, a| reflect::reflect_has_meta(a),
    /* 117 */ |_, a| reflect::reflect_get_meta_keys(a),
    /* 118..119 */ unimpl,
    unimpl,
    /* 120 */ async_::async_spawn,
    /* 121 */ async_::timer_set,
    /* 122 */ async_::timer_clear,
    /* 123 */ time::time_from_iso,
    /* 124 */ time::time_to_parts,
    /* 125 */ time::time_to_iso,
    /* 126 */ time::time_from_parts,
    /* 127..129 */ unimpl,
    unimpl,
    unimpl,
    /* 130 */ primitives::str_from_char_code,
    /* 131 */ primitives::str_length,
    /* 132 */ primitives::str_to_lower,
    /* 133 */ primitives::str_to_upper,
    /* 134 */ primitives::str_trim,
    /* 135 */ primitives::str_includes,
    /* 136 */ primitives::str_starts_with,
    /* 137 */ primitives::str_ends_with,
    /* 138 */ primitives::str_split,
    /* 139 */ primitives::str_substring,
    /* 140 */ primitives::str_char_at,
    /* 141 */ primitives::str_index_of,
    /* 142 */ primitives::int_parse,
    /* 143 */ primitives::int_to_str,
    /* 144 */ primitives::int_to_fixed,
    /* 145 */ primitives::int_abs,
    /* 146 */ primitives::float_parse,
    /* 147 */ primitives::float_to_str,
    /* 148 */ primitives::float_to_fixed,
    /* 149 */ primitives::float_abs,
    /* 150 */ primitives::char_to_str,
    /* 151 */ primitives::char_code_at,
    /* 152 */ array::array_length,
    /* 153 */ array::array_push,
    /* 154 */ array::array_pop,
    /* 155 */ array::array_shift,
    /* 156 */ array::array_unshift,
    /* 157 */ array::array_join,
    /* 158 */ array::array_includes,
    /* 159 */ array::array_index_of,
    /* 160 */ primitives::str_trim_start,
    /* 161 */ primitives::str_trim_end,
    /* 162 */ primitives::str_last_index_of,
    /* 163 */ primitives::str_slice,
    /* 164 */ primitives::str_replace,
    /* 165 */ primitives::str_replace_all,
    /* 166 */ primitives::str_char_code_at,
    /* 167 */ primitives::str_repeat,
    /* 168 */ primitives::str_pad_start,
    /* 169 */ primitives::str_pad_end,
    /* 170 */ primitives::str_concat,
    /* 171 */ primitives::str_substr,
    /* 172 */ primitives::str_is_empty,
    /* 173 */ primitives::str_is_blank,
    /* 174 */ primitives::str_is_digit,
    /* 175 */ primitives::str_is_letter,
    /* 176 */ primitives::str_is_whitespace,
    /* 177 */ primitives::str_reverse,
    /* 178 */ primitives::str_capitalize,
    /* 179 */ primitives::str_lines,
    /* 180 */ primitives::str_words,
    /* 181 */ primitives::str_to_int,
    /* 182 */ primitives::str_to_float,
    /* 183 */ primitives::str_from_value,
    /* 184..189 */ unimpl,
    unimpl,
    unimpl,
    unimpl,
    unimpl,
    unimpl,
    /* 190 */ primitives::int_sign,
    /* 191 */ primitives::int_negate,
    /* 192 */ primitives::int_bitwise_not,
    /* 193 */ primitives::int_min,
    /* 194 */ primitives::int_max,
    /* 195 */ primitives::int_clamp,
    /* 196 */ primitives::int_to_hex,
    /* 197 */ primitives::int_to_binary,
    /* 198 */ primitives::int_to_octal,
    /* 199 */ primitives::int_to_float,
    /* 200 */ primitives::int_pow,
    /* 201..209 */ unimpl,
    unimpl,
    unimpl,
    unimpl,
    unimpl,
    unimpl,
    unimpl,
    unimpl,
    unimpl,
    /* 210 */ primitives::float_sign,
    /* 211 */ primitives::float_negate,
    /* 212 */ primitives::float_min,
    /* 213 */ primitives::float_max,
    /* 214 */ primitives::float_pow,
    /* 215..219 */ unimpl,
    unimpl,
    unimpl,
    unimpl,
    unimpl,
    /* 220 */ array::array_slice,
    /* 221 */ array::array_at,
    /* 222 */ array::array_concat,
    /* 223 */ array::array_fill,
    /* 224 */ array::array_filter,
    /* 225 */ array::array_find,
    /* 226 */ array::array_find_index,
    /* 227 */ array::array_flat,
    /* 228 */ array::array_flat_map,
    /* 229 */ array::array_for_each,
    /* 230 */ array::array_map,
    /* 231 */ array::array_reduce,
    /* 232 */ array::array_reverse,
    /* 233 */ array::array_sort,
    /* 234 */ array::array_splice,
    /* 235 */ array::array_every,
    /* 236 */ array::array_some,
    /* 237..239 */ unimpl,
    unimpl,
    unimpl,
    /* 240 */ primitives::str_at,
    /* 241 */ primitives::str_code_point_at,
    /* 242..249 */ unimpl,
    unimpl,
    unimpl,
    unimpl,
    unimpl,
    unimpl,
    unimpl,
    unimpl,
    /* 250 */ primitives::int_is_integer,
    /* 251 */ primitives::float_is_nan,
    /* 252 */ primitives::float_is_finite,
    /* 253 */ primitives::float_is_integer,
];

pub fn dispatch_intrinsic(
    id: u16,
    ctx: &mut dyn tsn_types::Context,
    args: &[Value],
) -> Result<Value, String> {
    let f = INTRINSIC_TABLE
        .get(id as usize)
        .ok_or_else(|| format!("Unknown intrinsic ID: {}", id))?;
    f(ctx, args)
}
