#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum IntrinsicId {
    ConsoleLog = 0,
    JsonParse = 1,
    JsonStringify = 2,
    PathNormalize = 3,
    TimeNow = 4,
    ArrayIsArray = 5,

    MapNew = 6,
    MapGet = 7,
    MapSet = 8,
    MapHas = 9,

    IoWrite = 10,
    IoWriteln = 11,
    IoFlush = 12,
    IoReadLine = 13,
    IoReadAll = 14,

    MapDelete = 15,
    MapClear = 16,
    MapKeys = 17,
    MapValues = 18,
    MapSize = 19,

    SysPlatform = 20,
    SysCwd = 21,
    SysArgs = 22,
    SysExit = 23,
    SysEnvGet = 24,
    SysEnvSet = 25,

    SetNew = 26,
    SetAdd = 27,
    SetHas = 28,
    SetDelete = 29,

    FsRead = 30,
    FsWrite = 31,
    FsExists = 32,
    FsKind = 33,
    FsOpen = 34,
    FsCreate = 35,
    FsReadBytes = 36,
    FsReadText = 37,
    FsWriteBytes = 38,
    FsWriteText = 39,
    FsAppendText = 40,
    FsStat = 41,
    FsMkdir = 42,
    FsMkdirAll = 43,
    FsReadDir = 44,
    FsRemove = 45,
    FsRemoveAll = 46,
    FsRename = 47,
    FsCopy = 48,
    FsSymlink = 49,
    FsReadLink = 50,
    FsWatch = 51,
    FsTempDir = 52,

    SetClear = 53,
    SetValues = 54,
    SetSize = 55,

    ConsoleDebug = 56,

    CryptoSha256 = 60,
    CryptoSha512 = 61,
    CryptoRandomBytes = 62,
    CryptoRandomHex = 63,
    CryptoBase64Enc = 64,
    CryptoBase64Dec = 65,
    CryptoHmac = 66,
    CryptoUuid = 67,

    NetIsIp = 70,
    NetIsIpv4 = 71,
    NetIsIpv6 = 72,
    NetJoinHostPort = 73,
    NetSplitHostPort = 74,
    NetParseUrl = 75,
    NetResolveUrl = 76,
    NetParseQuery = 77,
    NetBuildQuery = 78,
    NetAppendQuery = 79,
    NetEncUriComponent = 80,
    NetDecUriComponent = 81,
    NetBasicAuth = 82,

    HttpFetch = 83,
    HttpServerCreate = 84,
    HttpServerRoute = 85,
    HttpServerListen = 86,
    HttpResponseSend = 87,

    MathAbs = 90,
    MathAcos = 91,
    MathAsin = 92,
    MathAtan = 93,
    MathAtan2 = 94,
    MathCeil = 95,
    MathCos = 96,
    MathExp = 97,
    MathFloor = 98,
    MathLog = 99,
    MathMax = 100,
    MathMin = 101,
    MathPow = 102,
    MathRandom = 103,
    MathRound = 104,
    MathSin = 105,
    MathSqrt = 106,
    MathTan = 107,
    MathTrunc = 108,
    MathSign = 109,
    MathNan = 110,
    MathInfinity = 111,
    SymbolIterator = 112,
    SymbolAsyncIterator = 113,

    ReflectDefineMeta = 114,
    ReflectGetMeta = 115,
    ReflectHasMeta = 116,
    ReflectGetMetaKeys = 117,

    AsyncSpawn = 120,
    TimerSet = 121,
    TimerClear = 122,
    TimeFromIso = 123,
    TimeToParts = 124,
    TimeToIso = 125,
    TimeFromParts = 126,

    StrFromCharCode = 130,
    StrLength = 131,
    StrToLower = 132,
    StrToUpper = 133,
    StrTrim = 134,
    StrIncludes = 135,
    StrStartsWith = 136,
    StrEndsWith = 137,
    StrSplit = 138,
    StrSubstring = 139,
    StrCharAt = 140,
    StrIndexOf = 141,
    IntParse = 142,
    IntToStr = 143,
    IntToFixed = 144,
    IntAbs = 145,
    FloatParse = 146,
    FloatToStr = 147,
    FloatToFixed = 148,
    FloatAbs = 149,
    CharToStr = 150,
    CharCodeAt = 151,
    ArrayLength = 152,
    ArrayPush = 153,
    ArrayPop = 154,
    ArrayShift = 155,
    ArrayUnshift = 156,
    ArrayJoin = 157,
    ArrayIncludes = 158,
    ArrayIndexOf = 159,

    StrTrimStart = 160,
    StrTrimEnd = 161,
    StrLastIndexOf = 162,
    StrSlice = 163,
    StrReplace = 164,
    StrReplaceAll = 165,
    StrCharCodeAt = 166,
    StrRepeat = 167,
    StrPadStart = 168,
    StrPadEnd = 169,
    StrConcat = 170,
    StrSubstr = 171,
    StrIsEmpty = 172,
    StrIsBlank = 173,
    StrIsDigit = 174,
    StrIsLetter = 175,
    StrIsWhitespace = 176,
    StrReverse = 177,
    StrCapitalize = 178,
    StrLines = 179,
    StrWords = 180,
    StrToInt = 181,
    StrToFloat = 182,
    StrFromValue = 183,

    AssertTest = 184,
    AssertSummary = 185,

    IntSign = 190,
    IntNegate = 191,
    IntBitwiseNot = 192,
    IntMin = 193,
    IntMax = 194,
    IntClamp = 195,
    IntToHex = 196,
    IntToBinary = 197,
    IntToOctal = 198,
    IntToFloat = 199,
    IntPow = 200,

    FloatSign = 210,
    FloatNegate = 211,
    FloatMin = 212,
    FloatMax = 213,
    FloatPow = 214,

    ArraySlice = 220,
    ArrayAt = 221,
    ArrayConcat = 222,
    ArrayFill = 223,
    ArrayFilter = 224,
    ArrayFind = 225,
    ArrayFindIndex = 226,
    ArrayFlat = 227,
    ArrayFlatMap = 228,
    ArrayForEach = 229,
    ArrayMap = 230,
    ArrayReduce = 231,
    ArrayReverse = 232,
    ArraySort = 233,
    ArraySplice = 234,
    ArrayEvery = 235,
    ArraySome = 236,

    StrAt = 240,
    StrCodePointAt = 241,

    IntIsInteger = 250,
    FloatIsNaN = 251,
    FloatIsFinite = 252,
    FloatIsInteger = 253,
}

impl IntrinsicId {
    #[inline]
    pub fn from_u16(v: u16) -> Option<Self> {
        match v {
            0..=9
            | 10..=19
            | 20..=29
            | 30..=56
            | 60..=67
            | 70..=87
            | 90..=117
            | 120..=126
            | 130..=185
            | 190..=200
            | 210..=214
            | 220..=236
            | 240..=241
            | 250..=253 => Some(unsafe { std::mem::transmute(v) }),
            _ => None,
        }
    }
}

pub fn resolve_intrinsic(name: &str) -> Option<IntrinsicId> {
    match name {
        "__console_log" => Some(IntrinsicId::ConsoleLog),
        "__console_debug" => Some(IntrinsicId::ConsoleDebug),
        "__array_is_array" => Some(IntrinsicId::ArrayIsArray),

        "__map_new" => Some(IntrinsicId::MapNew),
        "__map_get" => Some(IntrinsicId::MapGet),
        "__map_set" => Some(IntrinsicId::MapSet),
        "__map_has" => Some(IntrinsicId::MapHas),
        "__map_delete" => Some(IntrinsicId::MapDelete),
        "__map_clear" => Some(IntrinsicId::MapClear),
        "__map_keys" => Some(IntrinsicId::MapKeys),
        "__map_values" => Some(IntrinsicId::MapValues),
        "__map_size" => Some(IntrinsicId::MapSize),

        "__set_new" => Some(IntrinsicId::SetNew),
        "__set_add" => Some(IntrinsicId::SetAdd),
        "__set_has" => Some(IntrinsicId::SetHas),
        "__set_delete" => Some(IntrinsicId::SetDelete),
        "__set_clear" => Some(IntrinsicId::SetClear),
        "__set_values" => Some(IntrinsicId::SetValues),
        "__set_size" => Some(IntrinsicId::SetSize),
        "__json_parse" => Some(IntrinsicId::JsonParse),
        "__json_stringify" => Some(IntrinsicId::JsonStringify),
        "__path_normalize" => Some(IntrinsicId::PathNormalize),
        "__time_now" => Some(IntrinsicId::TimeNow),
        "__time_from_iso" => Some(IntrinsicId::TimeFromIso),
        "__time_to_parts" => Some(IntrinsicId::TimeToParts),
        "__time_to_iso" => Some(IntrinsicId::TimeToIso),
        "__time_to_iso_ms" => Some(IntrinsicId::TimeToIso),
        "__time_from_parts" => Some(IntrinsicId::TimeFromParts),

        "__io_write" => Some(IntrinsicId::IoWrite),
        "__io_writeln" => Some(IntrinsicId::IoWriteln),
        "__io_flush" => Some(IntrinsicId::IoFlush),
        "__io_read_line" => Some(IntrinsicId::IoReadLine),
        "__io_read_all" => Some(IntrinsicId::IoReadAll),

        "__sys_platform" => Some(IntrinsicId::SysPlatform),
        "__sys_cwd" => Some(IntrinsicId::SysCwd),
        "__sys_args" => Some(IntrinsicId::SysArgs),
        "__sys_exit" => Some(IntrinsicId::SysExit),
        "__sys_env_get" => Some(IntrinsicId::SysEnvGet),
        "__sys_env_set" => Some(IntrinsicId::SysEnvSet),

        "__fs_read" => Some(IntrinsicId::FsRead),
        "__fs_write" => Some(IntrinsicId::FsWrite),
        "__fs_exists" => Some(IntrinsicId::FsExists),
        "__fs_kind" => Some(IntrinsicId::FsKind),
        "__fs_open" => Some(IntrinsicId::FsOpen),
        "__fs_create" => Some(IntrinsicId::FsCreate),
        "__fs_read_bytes" => Some(IntrinsicId::FsReadBytes),
        "__fs_read_text" => Some(IntrinsicId::FsReadText),
        "__fs_write_bytes" => Some(IntrinsicId::FsWriteBytes),
        "__fs_write_text" => Some(IntrinsicId::FsWriteText),
        "__fs_append_text" => Some(IntrinsicId::FsAppendText),
        "__fs_stat" => Some(IntrinsicId::FsStat),
        "__fs_mkdir" => Some(IntrinsicId::FsMkdir),
        "__fs_mkdir_all" => Some(IntrinsicId::FsMkdirAll),
        "__fs_read_dir" => Some(IntrinsicId::FsReadDir),
        "__fs_remove" => Some(IntrinsicId::FsRemove),
        "__fs_remove_all" => Some(IntrinsicId::FsRemoveAll),
        "__fs_rename" => Some(IntrinsicId::FsRename),
        "__fs_copy" => Some(IntrinsicId::FsCopy),
        "__fs_symlink" => Some(IntrinsicId::FsSymlink),
        "__fs_read_link" => Some(IntrinsicId::FsReadLink),
        "__fs_watch" => Some(IntrinsicId::FsWatch),
        "__fs_temp_dir" => Some(IntrinsicId::FsTempDir),

        "__crypto_sha256" => Some(IntrinsicId::CryptoSha256),
        "__crypto_sha512" => Some(IntrinsicId::CryptoSha512),
        "__crypto_random_bytes" => Some(IntrinsicId::CryptoRandomBytes),
        "__crypto_random_hex" => Some(IntrinsicId::CryptoRandomHex),
        "__crypto_base64_enc" => Some(IntrinsicId::CryptoBase64Enc),
        "__crypto_base64_dec" => Some(IntrinsicId::CryptoBase64Dec),
        "__crypto_hmac" => Some(IntrinsicId::CryptoHmac),
        "__crypto_uuid" => Some(IntrinsicId::CryptoUuid),

        "__net_is_ip" => Some(IntrinsicId::NetIsIp),
        "__net_is_ipv4" => Some(IntrinsicId::NetIsIpv4),
        "__net_is_ipv6" => Some(IntrinsicId::NetIsIpv6),
        "__net_join_host_port" => Some(IntrinsicId::NetJoinHostPort),
        "__net_split_host_port" => Some(IntrinsicId::NetSplitHostPort),
        "__net_parse_url" => Some(IntrinsicId::NetParseUrl),
        "__net_resolve_url" => Some(IntrinsicId::NetResolveUrl),
        "__net_parse_query" => Some(IntrinsicId::NetParseQuery),
        "__net_build_query" => Some(IntrinsicId::NetBuildQuery),
        "__net_append_query" => Some(IntrinsicId::NetAppendQuery),
        "__net_enc_uri_component" => Some(IntrinsicId::NetEncUriComponent),
        "__net_dec_uri_component" => Some(IntrinsicId::NetDecUriComponent),
        "__net_basic_auth" => Some(IntrinsicId::NetBasicAuth),

        "__http_fetch" => Some(IntrinsicId::HttpFetch),
        "__http_server_create" => Some(IntrinsicId::HttpServerCreate),
        "__http_server_route" => Some(IntrinsicId::HttpServerRoute),
        "__http_server_listen" => Some(IntrinsicId::HttpServerListen),
        "__http_response_send" => Some(IntrinsicId::HttpResponseSend),

        "__math_abs" => Some(IntrinsicId::MathAbs),
        "__math_acos" => Some(IntrinsicId::MathAcos),
        "__math_asin" => Some(IntrinsicId::MathAsin),
        "__math_atan" => Some(IntrinsicId::MathAtan),
        "__math_atan2" => Some(IntrinsicId::MathAtan2),
        "__math_ceil" => Some(IntrinsicId::MathCeil),
        "__math_cos" => Some(IntrinsicId::MathCos),
        "__math_exp" => Some(IntrinsicId::MathExp),
        "__math_floor" => Some(IntrinsicId::MathFloor),
        "__math_log" => Some(IntrinsicId::MathLog),
        "__math_max" => Some(IntrinsicId::MathMax),
        "__math_min" => Some(IntrinsicId::MathMin),
        "__math_pow" => Some(IntrinsicId::MathPow),
        "__math_random" => Some(IntrinsicId::MathRandom),
        "__math_round" => Some(IntrinsicId::MathRound),
        "__math_sin" => Some(IntrinsicId::MathSin),
        "__math_sqrt" => Some(IntrinsicId::MathSqrt),
        "__math_tan" => Some(IntrinsicId::MathTan),
        "__math_trunc" => Some(IntrinsicId::MathTrunc),
        "__math_sign" => Some(IntrinsicId::MathSign),
        "__math_nan" => Some(IntrinsicId::MathNan),
        "__math_infinity" => Some(IntrinsicId::MathInfinity),
        "__symbol_iterator" => Some(IntrinsicId::SymbolIterator),
        "__symbol_async_iterator" => Some(IntrinsicId::SymbolAsyncIterator),

        "__reflect_define_meta" => Some(IntrinsicId::ReflectDefineMeta),
        "__reflect_get_meta" => Some(IntrinsicId::ReflectGetMeta),
        "__reflect_has_meta" => Some(IntrinsicId::ReflectHasMeta),
        "__reflect_get_meta_keys" => Some(IntrinsicId::ReflectGetMetaKeys),

        "__async_spawn" => Some(IntrinsicId::AsyncSpawn),
        "__timer_set" => Some(IntrinsicId::TimerSet),
        "__timer_clear" => Some(IntrinsicId::TimerClear),

        "__str_from_char_code" => Some(IntrinsicId::StrFromCharCode),
        "__str_length" => Some(IntrinsicId::StrLength),
        "__str_to_lower" => Some(IntrinsicId::StrToLower),
        "__str_to_upper" => Some(IntrinsicId::StrToUpper),
        "__str_trim" => Some(IntrinsicId::StrTrim),
        "__str_includes" => Some(IntrinsicId::StrIncludes),
        "__str_starts_with" => Some(IntrinsicId::StrStartsWith),
        "__str_ends_with" => Some(IntrinsicId::StrEndsWith),
        "__str_split" => Some(IntrinsicId::StrSplit),
        "__str_substring" => Some(IntrinsicId::StrSubstring),
        "__str_char_at" => Some(IntrinsicId::StrCharAt),
        "__str_index_of" => Some(IntrinsicId::StrIndexOf),
        "__int_parse" => Some(IntrinsicId::IntParse),
        "__int_to_str" => Some(IntrinsicId::IntToStr),
        "__int_to_fixed" => Some(IntrinsicId::IntToFixed),
        "__int_abs" => Some(IntrinsicId::IntAbs),
        "__float_parse" => Some(IntrinsicId::FloatParse),
        "__float_to_str" => Some(IntrinsicId::FloatToStr),
        "__float_to_fixed" => Some(IntrinsicId::FloatToFixed),
        "__float_abs" => Some(IntrinsicId::FloatAbs),
        "__char_to_str" => Some(IntrinsicId::CharToStr),
        "__char_code_at" => Some(IntrinsicId::CharCodeAt),
        "__array_length" => Some(IntrinsicId::ArrayLength),
        "__array_push" => Some(IntrinsicId::ArrayPush),
        "__array_pop" => Some(IntrinsicId::ArrayPop),
        "__array_shift" => Some(IntrinsicId::ArrayShift),
        "__array_unshift" => Some(IntrinsicId::ArrayUnshift),
        "__array_join" => Some(IntrinsicId::ArrayJoin),
        "__array_includes" => Some(IntrinsicId::ArrayIncludes),
        "__array_index_of" => Some(IntrinsicId::ArrayIndexOf),

        "__str_trim_start" => Some(IntrinsicId::StrTrimStart),
        "__str_trim_end" => Some(IntrinsicId::StrTrimEnd),
        "__str_last_index_of" => Some(IntrinsicId::StrLastIndexOf),
        "__str_slice" => Some(IntrinsicId::StrSlice),
        "__str_replace" => Some(IntrinsicId::StrReplace),
        "__str_replace_all" => Some(IntrinsicId::StrReplaceAll),
        "__str_char_code_at" => Some(IntrinsicId::StrCharCodeAt),
        "__str_repeat" => Some(IntrinsicId::StrRepeat),
        "__str_pad_start" => Some(IntrinsicId::StrPadStart),
        "__str_pad_end" => Some(IntrinsicId::StrPadEnd),
        "__str_concat" => Some(IntrinsicId::StrConcat),
        "__str_substr" => Some(IntrinsicId::StrSubstr),
        "__str_is_empty" => Some(IntrinsicId::StrIsEmpty),
        "__str_is_blank" => Some(IntrinsicId::StrIsBlank),
        "__str_is_digit" => Some(IntrinsicId::StrIsDigit),
        "__str_is_letter" => Some(IntrinsicId::StrIsLetter),
        "__str_is_whitespace" => Some(IntrinsicId::StrIsWhitespace),
        "__str_reverse" => Some(IntrinsicId::StrReverse),
        "__str_capitalize" => Some(IntrinsicId::StrCapitalize),
        "__str_lines" => Some(IntrinsicId::StrLines),
        "__str_words" => Some(IntrinsicId::StrWords),
        "__str_to_int" => Some(IntrinsicId::StrToInt),
        "__str_to_float" => Some(IntrinsicId::StrToFloat),
        "__str_from_value" => Some(IntrinsicId::StrFromValue),

        "__assert_test" => Some(IntrinsicId::AssertTest),
        "__assert_summary" => Some(IntrinsicId::AssertSummary),

        "__int_sign" => Some(IntrinsicId::IntSign),
        "__int_negate" => Some(IntrinsicId::IntNegate),
        "__int_bitwise_not" => Some(IntrinsicId::IntBitwiseNot),
        "__int_min" => Some(IntrinsicId::IntMin),
        "__int_max" => Some(IntrinsicId::IntMax),
        "__int_clamp" => Some(IntrinsicId::IntClamp),
        "__int_to_hex" => Some(IntrinsicId::IntToHex),
        "__int_to_binary" => Some(IntrinsicId::IntToBinary),
        "__int_to_octal" => Some(IntrinsicId::IntToOctal),
        "__int_to_float" => Some(IntrinsicId::IntToFloat),
        "__int_pow" => Some(IntrinsicId::IntPow),

        "__float_sign" => Some(IntrinsicId::FloatSign),
        "__float_negate" => Some(IntrinsicId::FloatNegate),
        "__float_min" => Some(IntrinsicId::FloatMin),
        "__float_max" => Some(IntrinsicId::FloatMax),
        "__float_pow" => Some(IntrinsicId::FloatPow),

        "__array_slice" => Some(IntrinsicId::ArraySlice),
        "__array_at" => Some(IntrinsicId::ArrayAt),
        "__array_concat" => Some(IntrinsicId::ArrayConcat),
        "__array_fill" => Some(IntrinsicId::ArrayFill),
        "__array_filter" => Some(IntrinsicId::ArrayFilter),
        "__array_find" => Some(IntrinsicId::ArrayFind),
        "__array_find_index" => Some(IntrinsicId::ArrayFindIndex),
        "__array_flat" => Some(IntrinsicId::ArrayFlat),
        "__array_flat_map" => Some(IntrinsicId::ArrayFlatMap),
        "__array_for_each" => Some(IntrinsicId::ArrayForEach),
        "__array_map" => Some(IntrinsicId::ArrayMap),
        "__array_reduce" => Some(IntrinsicId::ArrayReduce),
        "__array_reverse" => Some(IntrinsicId::ArrayReverse),
        "__array_sort" => Some(IntrinsicId::ArraySort),
        "__array_splice" => Some(IntrinsicId::ArraySplice),
        "__array_every" => Some(IntrinsicId::ArrayEvery),
        "__array_some" => Some(IntrinsicId::ArraySome),

        "__str_at" => Some(IntrinsicId::StrAt),
        "__str_code_point_at" => Some(IntrinsicId::StrCodePointAt),

        "__int_is_integer" => Some(IntrinsicId::IntIsInteger),
        "__float_is_nan" => Some(IntrinsicId::FloatIsNaN),
        "__float_is_finite" => Some(IntrinsicId::FloatIsFinite),
        "__float_is_integer" => Some(IntrinsicId::FloatIsInteger),

        _ => None,
    }
}
