use super::entry::{op, DispatchEntry};
use crate::modules::{async_, console, fs, io, json, path, reflect, sys, testing, time};
use tsn_core::intrinsic::IntrinsicId;

pub(crate) static OPS: &[DispatchEntry] = &[
    op(IntrinsicId::ConsoleLog, "console_log", console::console_log),
    op(IntrinsicId::ConsoleDebug, "console_debug", console::console_debug),
    op(IntrinsicId::JsonParse, "json_parse", json::json_parse),
    op(IntrinsicId::JsonStringify, "json_stringify", json::json_stringify),
    op(IntrinsicId::PathNormalize, "path_normalize", path::path_normalize),
    op(IntrinsicId::TimeNow, "time_now", time::time_now),
    op(IntrinsicId::TimeFromIso, "time_from_iso", time::time_from_iso),
    op(IntrinsicId::TimeToParts, "time_to_parts", time::time_to_parts),
    op(IntrinsicId::TimeToIso, "time_to_iso", time::time_to_iso),
    op(IntrinsicId::TimeFromParts, "time_from_parts", time::time_from_parts),
    op(IntrinsicId::IoWrite, "io_write", io::io_write),
    op(IntrinsicId::IoWriteln, "io_writeln", io::io_writeln),
    op(IntrinsicId::IoFlush, "io_flush", io::io_flush),
    op(IntrinsicId::IoReadLine, "io_read_line", io::io_read_line),
    op(IntrinsicId::IoReadAll, "io_read_all", io::io_read_all),
    op(IntrinsicId::SysPlatform, "sys_platform", sys::sys_platform),
    op(IntrinsicId::SysCwd, "sys_cwd", sys::sys_cwd),
    op(IntrinsicId::SysArgs, "sys_args", sys::sys_args),
    op(IntrinsicId::SysExit, "sys_exit", sys::sys_exit),
    op(IntrinsicId::SysEnvGet, "sys_env_get", sys::sys_env),
    op(IntrinsicId::SysEnvSet, "sys_env_set", sys::sys_set_env),
    op(IntrinsicId::FsRead, "fs_read", fs::fs_read),
    op(IntrinsicId::FsWrite, "fs_write", fs::fs_write),
    op(IntrinsicId::FsExists, "fs_exists", fs::fs_exists),
    op(IntrinsicId::FsKind, "fs_kind", fs::fs_stat),
    op(IntrinsicId::FsAppendText, "fs_append_text", fs::fs_append),
    op(IntrinsicId::FsStat, "fs_stat", fs::fs_stat),
    op(IntrinsicId::FsMkdir, "fs_mkdir", fs::fs_mkdir),
    op(IntrinsicId::FsMkdirAll, "fs_mkdir_all", fs::fs_mkdir_all),
    op(IntrinsicId::FsReadDir, "fs_read_dir", fs::fs_read_dir),
    op(IntrinsicId::FsRemove, "fs_remove", fs::fs_remove),
    op(IntrinsicId::FsRemoveAll, "fs_remove_all", fs::fs_remove_all),
    op(IntrinsicId::FsRename, "fs_rename", fs::fs_rename),
    op(IntrinsicId::FsCopy, "fs_copy", fs::fs_copy),
    op(IntrinsicId::FsTempDir, "fs_temp_dir", fs::fs_temp_dir),
    op(IntrinsicId::ReflectDefineMeta, "reflect_define_meta", reflect::reflect_define_meta),
    op(IntrinsicId::ReflectGetMeta, "reflect_get_meta", reflect::reflect_get_meta),
    op(IntrinsicId::ReflectHasMeta, "reflect_has_meta", reflect::reflect_has_meta),
    op(IntrinsicId::ReflectGetMetaKeys, "reflect_get_meta_keys", reflect::reflect_get_meta_keys),
    op(IntrinsicId::AsyncSpawn, "async_spawn", async_::async_spawn),
    op(IntrinsicId::TimerSet, "timer_set", async_::timer_set),
    op(IntrinsicId::TimerClear, "timer_clear", async_::timer_clear),
    op(IntrinsicId::AssertTest, "assert_test", testing::testing_assert),
    op(IntrinsicId::AssertSummary, "assert_summary", testing::testing_summary),
];