use super::entry::{op, DispatchEntry};
use crate::modules::{array, map, set};
use tsn_core::intrinsic::IntrinsicId;

pub(crate) static OPS: &[DispatchEntry] = &[
    op(IntrinsicId::ArrayIsArray, "array_is_array", array::array_is_array),
    op(IntrinsicId::MapNew, "map_new", map::map_new),
    op(IntrinsicId::MapGet, "map_get", map::map_get),
    op(IntrinsicId::MapSet, "map_set", map::map_set),
    op(IntrinsicId::MapHas, "map_has", map::map_has),
    op(IntrinsicId::MapDelete, "map_delete", map::map_delete),
    op(IntrinsicId::MapClear, "map_clear", map::map_clear),
    op(IntrinsicId::MapKeys, "map_keys", map::map_keys),
    op(IntrinsicId::MapValues, "map_values", map::map_values),
    op(IntrinsicId::MapSize, "map_size", map::map_size),
    op(IntrinsicId::SetNew, "set_new", set::set_new),
    op(IntrinsicId::SetAdd, "set_add", set::set_add),
    op(IntrinsicId::SetHas, "set_has", set::set_has),
    op(IntrinsicId::SetDelete, "set_delete", set::set_delete),
    op(IntrinsicId::SetClear, "set_clear", set::set_clear),
    op(IntrinsicId::SetValues, "set_values", set::set_values),
    op(IntrinsicId::SetSize, "set_size", set::set_size),
    op(IntrinsicId::ArrayLength, "array_length", array::array_length),
    op(IntrinsicId::ArrayPush, "array_push", array::array_push),
    op(IntrinsicId::ArrayPop, "array_pop", array::array_pop),
    op(IntrinsicId::ArrayShift, "array_shift", array::array_shift),
    op(IntrinsicId::ArrayUnshift, "array_unshift", array::array_unshift),
    op(IntrinsicId::ArrayJoin, "array_join", array::array_join),
    op(IntrinsicId::ArrayIncludes, "array_includes", array::array_includes),
    op(IntrinsicId::ArrayIndexOf, "array_index_of", array::array_index_of),
    op(IntrinsicId::ArraySlice, "array_slice", array::array_slice),
    op(IntrinsicId::ArrayAt, "array_at", array::array_at),
    op(IntrinsicId::ArrayConcat, "array_concat", array::array_concat),
    op(IntrinsicId::ArrayFill, "array_fill", array::array_fill),
    op(IntrinsicId::ArrayFilter, "array_filter", array::array_filter),
    op(IntrinsicId::ArrayFind, "array_find", array::array_find),
    op(IntrinsicId::ArrayFindIndex, "array_find_index", array::array_find_index),
    op(IntrinsicId::ArrayFlat, "array_flat", array::array_flat),
    op(IntrinsicId::ArrayFlatMap, "array_flat_map", array::array_flat_map),
    op(IntrinsicId::ArrayForEach, "array_for_each", array::array_for_each),
    op(IntrinsicId::ArrayMap, "array_map", array::array_map),
    op(IntrinsicId::ArrayReduce, "array_reduce", array::array_reduce),
    op(IntrinsicId::ArrayReverse, "array_reverse", array::array_reverse),
    op(IntrinsicId::ArraySort, "array_sort", array::array_sort),
    op(IntrinsicId::ArraySplice, "array_splice", array::array_splice),
    op(IntrinsicId::ArrayEvery, "array_every", array::array_every),
    op(IntrinsicId::ArraySome, "array_some", array::array_some),
];